### ISSUE TITLE
TIME command does not respond as expected

### ISSUE THREAD

**Issue by DMA57361** [sds/mock_redis#127] opened 2017-01-27 16:00 UTC
For example:
```
[1] pry(main)> require 'redis'
=> true
[2] pry(main)> require 'mock_redis'
=> true
[3] pry(main)> Redis.new.time
=> [1485530757, 588428]
[4] pry(main)> MockRedis.new.time
=> 2017-01-27 15:26:02 +0000
```

The expected behaviour of the [TIME](https://redis.io/commands/time) command is for it to return and array of two integers - the unix timestamp and the microseconds elapsed in the current second.

This is comparing the gems mock_redis version 0.17.1 and redis version 3.3.3 against a Redis server running version 3.2.6.

**Comment by trotzig** [comment] 2017-01-29 00:17
The behavior of time can be configured with the `time_class` option, added in https://github.com/brigade/mock_redis/commit/72a2580dbc54ad1878ee6aec473f19b0b41e50ee. It looks like the default could be altered to behave more like real redis however. Would you be willing to take this on in PR?

**Comment by DMA57361** [comment] 2017-01-29 10:28
I've had a quick look this morning:

The `time_class` you mention is what `MockRedis#now` (aliased as `time`, the method in question) uses, by simply calling `options[:time_class].now` ([code](https://github.com/brigade/mock_redis/blob/f2d1ff60ef0c8a7046404e1453ca744d49a96319/lib/mock_redis.rb#L67)). So, the initial expectation might be to just set the default `time_class` to be something that returns the expected array result when calling `now`. However, it looks like this will cause a breakage elsewhere, for example `MockRedis::DataBase#last_save` calls the `MockRedis#now` method and expects to call `to_i` on the result ([code](https://github.com/brigade/mock_redis/blob/f2d1ff60ef0c8a7046404e1453ca744d49a96319/lib/mock_redis/database.rb#L138)), this is going to fail if the return from `now` is an array. Deeper changes would be required for this approach.

Alternatively, removing the `time` alias and defining `time` as a new method that returns the expected array result could also work. Not sure if you're happy for `#now` and `#time` for diverge, or what other impact within the gem this could have. I might be able to find time to just try it and run the specs this evening or probably tomorrow morning.

**Comment by DMA57361** [comment] 2017-01-30 08:56
Cloned the gem this morning and I'm getting 3 spec failures before I've started making any changes. I'm assuming something's up with my local setup (I've tried both Ruby 2.3.1 & 2.4.0, local Redis on this machine is 3.2.4). I'd rather not submit a pull request rewritten on an unstable test suite and I don't really wish to dig around in the gem to figure out the cause. (I'm guessing wrong local Redis version? I don't fancy repeatedly installing different versions until I find one that works, but if you know a specific version that should work I'll give it a try).

Here's the failures in case it's something obvious you can point me to:

```
  1) #rename(key, newkey) raises an error when key == newkey
     Failure/Error:
       lambda do
         @redises.rename(@key, @key)
       end.should raise_error(Redis::CommandError)

       expected Redis::CommandError, got #<RedisMultiplexer::MismatchedResponse: Mock failure: raised an error when it shouldn't have.
       Redis.r...s-test:rename:key"]) raised #<Redis::CommandError: ERR source and destination objects are the same>> with backtrace:
         # ./spec/support/redis_multiplexer.rb:56:in `method_missing'
         # ./spec/commands/rename_spec.rb:29:in `block (3 levels) in <top (required)>'
         # ./spec/commands/rename_spec.rb:28:in `block (2 levels) in <top (required)>'
     # ./spec/commands/rename_spec.rb:28:in `block (2 levels) in <top (required)>'

<snipped two almost-identical backtraces>

Failed examples:

rspec ./spec/commands/rename_spec.rb:27 # #rename(key, newkey) raises an error when key == newkey
rspec ./spec/commands/renamenx_spec.rb:32 # #renamenx(key, newkey) raises an error when key == newkey
rspec ./spec/commands/spop_spec.rb:24 # #spop(key) it should behave like a set-only command raises an error for non-set values
```

**Comment by trotzig** [comment] 2017-01-30 18:12
I don't have enough context to quickly determine why you are seeing those errors, but I think your assumption about redis version playing a role seems likely. I just ran the same thing locally and I get the same errors. I'm on redis-server v3.0.4 myself. 

Any chance @smerritt or @sds has any context on this? tl;dr - we're seeing specs fail because we're expecting `Redis::CommandError` but we're getting `RedisMultiplexer::MismatchedResponse`.

**Comment by sds** [comment] 2017-01-31 08:18
The test suite passes for me with Redis 3.0.7 (built and compiled from scratch just now). 

The last pull request that was merged (#125) [ran against Redis 3.0.6 without issue](https://travis-ci.org/brigade/mock_redis/jobs/175894670).

Travis CI unfortunately doesn't do a good job of documenting when they update Redis, but we can create a dummy pull request to find out which version they use and make sure we test against that.

With all that said, it sounds like @DMA57361 might need to switch to Redis 3.0.x when writing his pull request. [Instructions to installing it are pretty straightforward](https://redis.io/download#installation).

Would also be open to updating the test suite to work with a newer version of Redis, but that may require updating the `.travis.yml` file to manually install the Redis version we desire (perhaps altering the matrix to test multiple Redis versions to ensure compatibility).

**Comment by DMA57361** [comment] 2017-01-31 09:02
I've now just downloaded, built and tried each of 3.0.4, 3.0.6 and 3.0.7. Each was run as `﻿﻿./redis-server --dbfilename local.db` (to keep the DB separate from my system installed Redis) so I assume they have whatever the default config is. For each of those I now get one error, the same in each case. It is one of the three I was seeing before:

```
  1) #spop(key) it should behave like a set-only command raises an error for non-set values
     Failure/Error:
       lambda do
         @redises.send(method, *args)
       end.should raise_error(RuntimeError)

       expected RuntimeError, got #<RedisMultiplexer::MismatchedResponse: Mock failure: raised the wrong error.
       Redis.send(["spop", "mo...dis-test:set-only", 1, 2]) raised #<ArgumentError: wrong number of arguments (given 3, expected 1)>> with backtrace:
         # ./spec/support/redis_multiplexer.rb:61:in `method_missing'
         # ./spec/support/shared_examples/only_operates_on_sets.rb:10:in `block (3 levels) in <top (required)>'
         # ./spec/support/shared_examples/only_operates_on_sets.rb:9:in `block (2 levels) in <top (required)>'
     Shared Example Group: "a set-only command" called from ./spec/commands/spop_spec.rb:24
     # ./spec/support/shared_examples/only_operates_on_sets.rb:9:in `block (2 levels) in <top (required)>'
```

**Comment by sds** [comment] 2017-02-01 04:27
I can reproduce that failure with version 3.3.3 of the `redis` gem, but _not_ version 3.3.1 (which is what I was running with previously), both on Ruby 2.3.3 and 2.4.0. Looks like https://github.com/redis/redis-rb/pull/628 broke something with `spop`.

Would appreciate a pull request fixing the issue, as I don't have time to investigate further. Thanks!

**Closed** 2019-05-07 16:31 UTC
Labels: bug
